version: '3.7'
services:
  frontend:
    container_name: dt-front-dev
    image: dt-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped
    volumes:
      - "./src:/usr/src/app/src"
    command: sh -c "$$(npm bin)/ng serve --host 0.0.0.0 --port ${APP_PORT}"
